### ISSUE TITLE
Question re: cljs.tools.reader vs cljs.reader

### ISSUE THREAD

**Issue by ptaoussanis** [clojure/tools.reader#10]
Hi Nicola,

I noticed that tools.reader 0.10+ has ClojureScript support, is that right? Tried searching to come up with some more info on this but couldn't find any (sorry if I missed it).

As of 0.10- any particular reason for users to prefer tools.reader vs cljs.reader? Any major differences expected in performance or stability, etc.? Any plans for the implementations to eventually merge?

Thanks so much! Cheers :-)

**Comment by Bronsa** [comment]
cljs.reader is just an edn reader, tools.reader provides both an edn and a full clojurescript reader.
tools.reader's edn reader implementation is probably faster than cljs.reader aswell

**Comment by ptaoussanis** [comment]
Thanks a lot, appreciate your feedback (and work!)

So just to clarify: if reading only edn- the two are functionally similar, similarly mature/reliable, but tools.reader might be a little faster? I.e. no particular reason to ever prefer cljs.reader for new projects if you already have a tools.reader dependency, yes?

**Comment by Bronsa** [comment]
Correct. I haven't done much work in the cljs port of tools.reader but it has been exstensively benchmarked and optimized by david nolen, so I'm sure it's as fast as it can be
