### ISSUE TITLE
Is there a way to read EDN while keeping line and column numbers?

### ISSUE THREAD

**Issue by fredZen** [clojure/tools.reader#16]
I'd like to parse untrusted data while retaining line and column numbers.

`clojure.tools.reader/read` isn’t recommended for untrusted data, because it can execute it.
And as far as I can tell, `clojure.tools.reader.edn/read` doesn’t attach line and column numbers as metadata like `clojure.tools.reader/read`does (assuming the underlying reader supports it). 

As a workaround, I was considering using the unsafe `clojure.tools.reader/read`, but binding `*data-readers*` to a map of know-safe readers, and `*read-eval*` to `false`.

Would that still leave me open to, er, we'd call them Clojure injection attacks, I guess?

(edited to change `*suppress-read*`, which made no sense, to `*read-eval*`)

**Comment by puredanger** [comment]
Hi, this project does not use GitHub issues. You can ask questions or file issues at https://ask.clojure.org. Thanks!
