### ISSUE TITLE
No metadata on clojure 1.9 map literals

### ISSUE THREAD

**Issue by fredZen** [clojure/tools.reader#17]
Maps written using the new `#:default.namespace{,,,}` syntax don't get file positions attached as metadata.

Given this setup code

```clojure
(require '[clojure.tools.reader :as reader])
(require '[clojure.tools.reader.reader-types :as reader-types])

(defn sample [s]
  (with-open [r (java.io.StringReader. s)]
    (meta (reader/read (reader-types/indexing-push-back-reader (reader-types/push-back-reader r) 1)))))
```

this edn literal fails to get parsed with positional metadata
```clojure
(sample "#:ns{ :key :val }") ; => nil
```

unlike those two, which get their positional metadata as expected
```clojure
(sample "{ :key :val }")     ; => {:line 1, :column 1, :end-line 1, :end-column 14}
(sample "{ :ns/key val }")   ; => {:line 1, :column 1, :end-line 1, :end-column 16}
```

**Comment by puredanger** [comment]
Hi, this project does not use GitHub issues. You can add this as a question at https://ask.clojure.org and I can generate a ticket from there.

Thanks...
