### ISSUE TITLE
reading sequence breakage with a semicolon

### ISSUE THREAD

**Issue by spacegangster** [clojure/tools.reader#19]
Hey encountered this issue while playing with my Clojurescript REPL. Which uses tools.reader when syncing files to a REPL.
Then Thomas Heller reduced it further to:

```
(let [rdr (clojure.tools.reader.reader-types/source-logging-push-back-reader
            "(ns demo.test)\n\n(def foo \"foo\");\n(def bar [])\n")]
  (clojure.tools.reader/read+string rdr)
  (clojure.tools.reader/read+string rdr)
  (clojure.tools.reader/read+string rdr))
```

Clojurians Slack thread [here](https://clojurians.slack.com/archives/C6N245JGG/p1686561981177639).

**Comment by puredanger** [comment]
Hello, this project does not use GitHub issues - please file a question at https://ask.clojure.org in the "Contrib libs" / tools.reader category.
